name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CD
        run: echo 'CD is Disabled (Check workflow comment for the code).'

      - name: Deploy using ssh
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/apps/ga-ci-cd-nodejs
            git pull origin master
            git status
            npm install --only=prod
            pm2 restart YoutubeApp
